name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10', '12', '14' ]
    name: Node ${{ matrix.node }} build
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm i
      - name: Run build
        run: npm run build
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10', '12', '14' ]
    name: Node ${{ matrix.node }} test
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm run test
  publish:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [build, test]
    name: Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm i
      - name: Run build
        run: npm run build
      - name: Run publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Tag
        uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "v"
